#ifndef MODELVIEWER_UTILS_PREDEFINE_ARCHITECTURE_WINDOWS_HPP_
#define MODELVIEWER_UTILS_PREDEFINE_ARCHITECTURE_WINDOWS_HPP_

#if defined(_WIN64) || defined(_WIN32)
    #if defined(_WIN64)
        #define PROGRAM_ENVIRONMENT_64BIT
    #else
        #define PROGRAM_ENVIRONMENT_32BIT
    #endif
#endif

#endif // MODELVIEWER_UTILS_PREDEFINE_ARCHITECTURE_WINDOWS_HPP_
